// <auto-generated />
namespace PhantomNet.AspNetCore.Mvc
{
    using System.Globalization;
    using System.Reflection;
    using System.Resources;

    internal static class Resources
    {
        private static readonly ResourceManager _resourceManager
            = new ResourceManager("PhantomNet.AspNetCore.Mvc.Resources", typeof(Resources).GetTypeInfo().Assembly);

        /// <summary>
        /// A tag with '{0}' attribute must have at least one of the following: '{1}' attribute, '{2}' attribute, an ancestor which is a form tag with '{3}' attribute, or an ancestor which is a form tag with '{4}' attribute.
        /// </summary>
        internal static string AngularInputGroupTagHelper_CssClassRequired
        {
            get { return GetString("AngularInputGroupTagHelper_CssClassRequired"); }
        }

        /// <summary>
        /// A tag with '{0}' attribute must have at least one of the following: '{1}' attribute, '{2}' attribute, an ancestor which is a form tag with '{3}' attribute, or an ancestor which is a form tag with '{4}' attribute.
        /// </summary>
        internal static string FormatAngularInputGroupTagHelper_CssClassRequired(object p0, object p1, object p2, object p3, object p4)
        {
            return string.Format(CultureInfo.CurrentCulture, GetString("AngularInputGroupTagHelper_CssClassRequired"), p0, p1, p2, p3, p4);
        }

        /// <summary>
        /// A tag with '{0}' attribute must have '{1}' attribute or have an ancestor which is a form tag with '{2}' attribute.
        /// </summary>
        internal static string FormNameOrAngularFormRequired
        {
            get { return GetString("FormNameOrAngularFormRequired"); }
        }

        /// <summary>
        /// A tag with '{0}' attribute must have '{1}' attribute or have an ancestor which is a form tag with '{2}' attribute.
        /// </summary>
        internal static string FormatFormNameOrAngularFormRequired(object p0, object p1, object p2)
        {
            return string.Format(CultureInfo.CurrentCulture, GetString("FormNameOrAngularFormRequired"), p0, p1, p2);
        }

        private static string GetString(string name, params string[] formatterNames)
        {
            var value = _resourceManager.GetString(name);

            System.Diagnostics.Debug.Assert(value != null);

            if (formatterNames != null)
            {
                for (var i = 0; i < formatterNames.Length; i++)
                {
                    value = value.Replace("{" + formatterNames[i] + "}", "{" + i + "}");
                }
            }

            return value;
        }
    }
}
