//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhantomNet.Mvc {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal Resources() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PhantomNet.Mvc.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to A tag with &apos;pn-ng-group-for&apos; attribute must have at least one of the following: &apos;error-css-class&apos; attribute, &apos;bootstrap-style&apos; attribute, an ancestor which is a form tag with &apos;error-css-class&apos; attribute, or an ancestor which is a form tag with &apos;bootstrap-style&apos; attribute..
        /// </summary>
        public static string AngularInputGroupTagHelper_ErrorCssClassRequired {
            get {
                return ResourceManager.GetString("AngularInputGroupTagHelper_ErrorCssClassRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to A tag with &apos;pn-ng-group-for&apos; attribute must have &apos;form-name&apos; attribute or have an ancestor which is a form tag with &apos;pn-ng-name&apos; attribute..
        /// </summary>
        public static string AngularInputGroupTagHelper_FormNameOrAngularFormRequired {
            get {
                return ResourceManager.GetString("AngularInputGroupTagHelper_FormNameOrAngularFormRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to A tag with &apos;pn-ng-group-for&apos; attribute must have at least one of the following: &apos;success-css-class&apos; attribute, &apos;bootstrap-style&apos; attribute, an ancestor which is a form tag with &apos;success-css-class&apos; attribute, or an ancestor which is a form tag with &apos;bootstrap-style&apos; attribute..
        /// </summary>
        public static string AngularInputGroupTagHelper_SuccessCssClassRequired {
            get {
                return ResourceManager.GetString("AngularInputGroupTagHelper_SuccessCssClassRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to A tag with &apos;pn-ng-submit&apos; attribute must have &apos;form-name&apos; attribute or have an ancestor which is a form tag with &apos;pn-ng-name&apos; attribute..
        /// </summary>
        public static string AngularSubmitButtonTagHelper_FormNameOrAngularFormRequired {
            get {
                return ResourceManager.GetString("AngularSubmitButtonTagHelper_FormNameOrAngularFormRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to A tag with &apos;pn-ng-validation-for&apos; attribute must have &apos;form-name&apos; attribute or have an ancestor which is a form tag with &apos;pn-ng-name&apos; attribute..
        /// </summary>
        public static string AngularValidationMessageTagHelper_FormNameOrAngularFormRequired {
            get {
                return ResourceManager.GetString("AngularValidationMessageTagHelper_FormNameOrAngularFormRequired", resourceCulture);
            }
        }
    }
}
